const { define } = require('./utils/utils');

const craftBase = require('./libs/craft');
const { formatGraphQLError } = require('./libs/error');
const { defaultOptions } = require('./options');
const { copyMissing } = require('./utils');
const permissions = require('./permissions');


const init = (options) => {

  options = copyMissing(options, defaultOptions);

  options.dataloaderContext = null;

  const resetCache = () => {
    if (
      options.dataloaderContext &&
      options.dataloaderContext.loaders.autogenerated
    ) {
      options.dataloaderContext.loaders.autogenerated.reset();
    }
  };

  const craft = craftBase(options);

  return {
    craft,
    generateSchema: craft,
    // reset dataloader cache, recommended to be used at the end of each request when working with aws lambda
    resetCache,
    // Other utils that can be exported
    // should be defined here
    // TODO: maybe better to use a class
    // export multiple things in the common way
    define,
    // use this to prime custom queries
    dataloaderContext: options.dataloaderContext,
    errorHandler: formatGraphQLError
  };
};

init.permissions = permissions;

module.exports = init;

/*
rules: {
  fetch: {
    resources: [
      {
        model: "Job",
        fields: ["id", "number"],
        conditions: [
          { field: "userId", value: ":ctx.user.id" },
          { field: "status", value: true },
        ],
      },
    ];
  }
}
*/
