const assert = require('assert');
const cls = require('cls-hooked');
const TRANSACTION_NAMESPACE = 'sequelize-graphql-schema';
const { createContext } = require('dataloader-sequelize');
const { define } = require('./utils');

const { defaultOptions, defaultModelGraphqlOptions } = require('./options');

const GenerateQueries = require('./libs/generateQueries');
const GenerateMutations = require('./libs/generateMutations');
const GenerateTypes = require('./libs/generateTypes');
const errorHandler = (options) => {
  return (error) => {
    for (const name in options.errorHandler) {
      if (error.message.indexOf(name) > -1) {
        Object.assign(error, options.errorHandler[name]);
        break;
      }
    }

    return error;
  };
};

function generateSchema(options) {
  return async (models, context) => {
    assert(models.Sequelize, 'Sequelize not found as models.Sequelize.');
    assert(
      models.sequelize,
      'sequelize instance not found as models.sequelize.'
    );

    if (options.dataloader) {
      options.dataloaderContext = createContext(models.sequelize);
    }

    options.Sequelize = models.Sequelize;
    options.sequelize = models.sequelize;
    options.models = models;

    const generatedPermissions = await options.permissions({
      models,
      ...context,
    });

    options.GC_PERMISSIONS = { strict: true, ...generatedPermissions };

    options.Sequelize.useCLS(cls.createNamespace(TRANSACTION_NAMESPACE));

    const { generateModelTypes } = GenerateTypes(options);
    const generateQueries = GenerateQueries(options);
    const generateMutations = GenerateMutations(options);
    const modelsIncluded = {};

    for (const modelName in models) {
      const model = models[modelName];

      if (
        'name' in model &&
        modelName !== 'Sequelize' &&
        !options.exclude.includes(modelName)
      ) {
        model.graphql = model.graphql || defaultModelGraphqlOptions;
        model.graphql.attributes = Object.assign(
          {},
          defaultModelGraphqlOptions.attributes,
          model.graphql.attributes
        );
        model.graphql = Object.assign(
          {},
          defaultModelGraphqlOptions,
          model.graphql
        );
        modelsIncluded[modelName] = model;
      }
    }

    const modelTypes = generateModelTypes(modelsIncluded, {}, options);

    return Promise.resolve({
      query: generateQueries(
        modelsIncluded,
        modelTypes.outputTypes,
        modelTypes.inputTypes
      ),
      mutation: generateMutations(
        modelsIncluded,
        modelTypes.outputTypes,
        modelTypes.inputTypes
      ),
    });
  };
}

const init = (_options) => {
  const newOptions = { ..._options };

  newOptions.naming = Object.assign(
    {},
    defaultOptions.naming,
    newOptions.naming
  );
  newOptions.naming.type = Object.assign(
    {},
    defaultOptions.naming.type,
    newOptions.naming.type
  );
  newOptions.exposeOnly = Object.assign(
    {},
    defaultOptions.exposeOnly,
    newOptions.exposeOnly
  );
  newOptions.limits = Object.assign(
    {},
    defaultOptions.limits,
    newOptions.limits
  );

  const options = Object.assign({}, defaultOptions, newOptions);

  options.dataloaderContext = null;

  const resetCache = () => {
    if (
      options.dataloaderContext &&
      options.dataloaderContext.loaders.autogenerated
    ) {
      options.dataloaderContext.loaders.autogenerated.reset();
    }
  };

  return {
    generateSchema: generateSchema(options),
    // reset dataloader cache, recommended to be used at the end of each request when working with aws lambda
    resetCache,
    // use this to prime custom queries
    dataloaderContext: options.dataloaderContext,
    errorHandler: errorHandler(options),
  };
};

// Other utils that can be exported
// should be defined here
// TODO: maybe better to use a class
// export multiple things in the common way
init.define = define;

module.exports = init;

/*
rules: {
  fetch: {
    resources: [
      {
        model: "Job",
        fields: ["id", "number"],
        conditions: [
          { field: "userId", value: ":ctx.user.id" },
          { field: "status", value: true },
        ],
      },
    ];
  }
}
*/
